/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type { ISwapper, ISwapperInterface } from '../../../contracts/interfaces/ISwapper';

const _abi = [
  {
    inputs: [
      {
        internalType: 'bytes',
        name: 'data',
        type: 'bytes',
      },
    ],
    name: 'onSwapReceived',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];

export class ISwapper__factory {
  static readonly abi = _abi;
  static createInterface(): ISwapperInterface {
    return new utils.Interface(_abi) as ISwapperInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ISwapper {
    return new Contract(address, _abi, signerOrProvider) as ISwapper;
  }
}
